name: Daily Commit Automation

on:
  schedule:
    # Runs daily at 07:00 UTC
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dummy file with email 23f2000595@ds.study.iitm.ac.in
        run: |
          echo "Daily update $(date)" >> daily_update.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "23f2000595@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Actions Bot"
          git add daily_update.txt
          git commit -m "Daily automated commit [skip ci]" || echo "No changes to commit"
          git push
